[relaychain]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1234
default_command = "./target/release/parachain-from-scratch-node"

[[parachains.collators]]
name = "collator-01"

[[parachains.collators]]
name = "collator-02"
